export { default as RegisterIlustrationSvg } from './RegisterIlustration'
export { default as JoySvg } from './Joy'
export { default as LoginIllustration } from './LoginIllustration'
export { default as ForgotPasswordSvg } from './ForgotPassword'
export { default as SentEmailSvg } from './SentEmail'
export { default as PTLCC } from './PTLCC'
